[package]
name = "esp-idf-svc"
version = "0.53.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "idf", "esp-idf", "esp32"]
description = "Implementation of the embedded-svc traits for ESP-IDF (Espressif's IoT Development Framework)"
readme = "README.md"
links = "esp_idf_svc"
build = "build.rs"
documentation = "https://esp-rs.github.io/esp-idf/esp-idf-svc"

[lib]
harness = false

[features]
default = ["std", "binstart"]

std = ["alloc", "log/std", "esp-idf-hal/std", "embedded-svc/std", "futures-io"]
embassy-time-driver = ["dep:embassy-time-driver", "embassy-time-queue-utils"]
alloc = ["esp-idf-hal/alloc", "embedded-svc/alloc", "uncased/alloc"]
nightly = ["embedded-svc/nightly", "esp-idf-hal/nightly"]
experimental = ["embedded-svc/experimental", "esp-idf-hal/experimental"]

# Propagated esp-idf-hal features
critical-section = ["esp-idf-hal/critical-section"]
wake-from-isr = ["esp-idf-hal/wake-from-isr"]
embassy-sync = ["esp-idf-hal/embassy-sync"]

# The next are propagated from esp-idf-sys via esp-idf-hal
native = ["esp-idf-hal/native"]
pio = ["esp-idf-hal/pio"]
alloc_handler = ["esp-idf-hal/alloc_handler"]
panic_handler = ["esp-idf-hal/panic_handler"]
binstart = ["esp-idf-hal/binstart"]
libstart = ["esp-idf-hal/libstart"]

# Propagated form embeded-svc
use_serde = ["embedded-svc/use_serde"]

[dependencies]
heapless = { workspace = true }
num_enum = { workspace = true }
enumset = { workspace = true }
log = { workspace = true }
uncased = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-svc = { workspace = true }
esp-idf-hal = { workspace = true }
embassy-time-driver = { workspace = true, optional = true }
embassy-time-queue-utils = { workspace = true, optional = true }
embassy-futures = { workspace = true }
embedded-storage = { workspace = true, optional = true }
futures-io = { workspace = true, optional = true }

[build-dependencies]
embuild = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
esp-idf-sys = { workspace = true, features = ["std", "binstart"] }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
async-io = { workspace = true }
