[package]
name = "esp-idf-hal"
version = "0.47.0"
authors = ["sapir <yasapir@gmail.com>", "Ivan Markov <ivan.markov@gmail.com>"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
categories = ["embedded", "hardware-support"]
keywords = ["hal", "idf", "esp-idf", "esp32"]
description = "A Hardware abstraction layer for Espressif's ESP family of microcontrollers based on the ESP-IDF framework."
readme = "README.md"
links = "esp_idf_hal"
build = "build.rs"
documentation = "https://esp-rs.github.io/esp-idf/esp-idf-hal"

[lib]
harness = false

[features]
default = ["std", "binstart"]
std = ["alloc", "esp-idf-sys/std"]
alloc = []
nightly = []
experimental = []
wake-from-isr = [] # Only enable if you plan to use the `edge-executor` crate
embassy-sync = [] # For now, the dependecy on the `embassy-sync` crate is non-optional, but this might change in future
# Temporary, until (https://github.com/espressif/esp-idf/issues/13938) is addressed
# - When enabled, the code for the legacy ADC oneshot driver will be compiled;
# - When not enabled (default) the code for the new ADC oneshot driver will be compiled;
# - Since we don't wrap the legacy _continuous_ ADC driver, the new _continuous_ ADC driver is always compiled.
adc-oneshot-legacy = []
# Similar to adc-oneshot-legacy
# - When enabled (default), the code for the legacy RMT TX/RX driver will be compiled.
# - When disabled the code for the new onewire RMT driver will be compiled.
rmt-legacy = []
# Propagated esp-idf-sys features
native = ["esp-idf-sys/native"]
pio = ["esp-idf-sys/pio"]
alloc_handler = ["esp-idf-sys/alloc_handler"]
panic_handler = ["esp-idf-sys/panic_handler"]
binstart = ["esp-idf-sys/binstart"]
libstart = ["esp-idf-sys/libstart"]
# Similar to rmt-legacy
# - When enabled, the code for the legacy driver will be compiled.
# - When disabled the code for the new driver will be compiled.
pcnt-legacy = []
# Similar to pcnt-legacy
# - When enabled, the code for the legacy driver will be compiled.
# - When disabled the code for the new driver will be compiled.
timer-legacy = []
embedded-graphics = ["dep:embedded-graphics-core"]

[dependencies]
nb = { workspace = true }
embedded-can = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-0-2 = { workspace = true }
embedded-hal-nb = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-io = { workspace = true }
embedded-io-async = { workspace = true }
esp-idf-sys = { workspace = true }
critical-section = { workspace = true, optional = true }
heapless = { workspace = true }
enumset = { workspace = true }
log = { workspace = true }
atomic-waker = { workspace = true }
embassy-sync = { workspace = true }
embedded-graphics-core = { workspace = true, optional = true }

[build-dependencies]
embuild = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
esp-idf-sys = { workspace = true, features = ["std", "binstart"] }
mipidsi = { workspace = true }
display-interface-spi = { workspace = true }
embedded-graphics = { workspace = true }
