[package]
name = "esp-idf-sys"
version = "0.38.1"
authors = ["Alexey Arbuzov <aarbuzov@termt.com>", "sapir <yasapir@gmail.com>", "Ivan Markov <ivan.markov@gmail.com>", "Dominik Gschwind <dominik.gschwind99@gmail.com>"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
categories = ["embedded", "hardware-support"]
keywords = ["sys", "idf", "esp-idf", "esp32"]
description = "Bindings for ESP-IDF (Espressif's IoT Development Framework)"
readme = "README.md"
links = "esp_idf"
build = "build/build.rs"
documentation = "https://esp-rs.github.io/esp-idf/esp-idf-sys"

[lib]
harness = false

[features]
default = ["std", "binstart"]

std = []
alloc_handler = []
panic_handler = []
binstart = []
libstart = []
native = []
pio = ["embuild/pio"]

[dependencies]
libc = { workspace = true } # For compile-time libc compatibility checks
compile-fmt = { workspace = true } # For compile-time libc compatibility checks
build-time = { workspace = true }   # For esp_app_desc!()
const_format = { workspace = true } # For esp_app_desc!()

[build-dependencies]
embuild = { workspace = true, features = ["glob", "kconfig", "cmake", "espidf"] }
anyhow = { workspace = true }
regex = { workspace = true }
cmake = { workspace = true }
cargo_metadata = { workspace = true }
serde = { workspace = true, features = ["std"] }
strum = { workspace = true }
envy = { workspace = true }
toml = { workspace = true }
which = { workspace = true }
